на ревью
TauCetiStation-TranslationDepartment/TauCetiClassic pull request #34
Opened 2024-05-28 12:52 UTC by maleyvich

## Описание изменений

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2024-05-28 12:59 UTC, Pivo24 requested changes

2024-05-28 12:59 UTC, Pivo24 commented on code/modules/mob/dead/new_player/new_player.dm
> +			to_chat(usr, "<span class='notice'>Администрация заблокировала вход в игру!</span>")
Стоит как-то перефразировать, я сначала про паник-бункер подумал или типа того.

Администрация отключила вступление в раунд?

Тут как-то акцент на том, что гостота всё ещё может.

2024-05-28 12:59 UTC, Pivo24 commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(usr, "<span class='notice'>Администрация заблокировала вход в игру!</span>")
Ну, как и тут

2024-05-28 12:59 UTC, Pivo24 commented on code/modules/mob/dead/new_player/new_player.dm
> +		which_time_is_it = "<b>[mins]</b> минут."
4 минут?

2024-05-28 12:59 UTC, Pivo24 commented on code/modules/mob/dead/new_player/new_player.dm
> +			which_time_is_it = "<b>[hours]</b> часов and [which_time_is_it]"
4 часов?

2024-05-28 13:05 UTC, maleyvich commented on code/modules/mob/dead/new_player/new_player.dm
> +			which_time_is_it = "<b>[hours]</b> часов and [which_time_is_it]"
я забыл че над использовать для времени блииин

2024-05-28 13:05 UTC, maleyvich commented on code/modules/mob/dead/new_player/new_player.dm
> +		which_time_is_it = "<b>[mins]</b> минут."
аналогично

2024-05-28 13:06 UTC, maleyvich commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(usr, "<span class='notice'>Администрация заблокировала вход в игру!</span>")
норм

2024-05-30 08:45 UTC, AzzyDreemurr13 requested changes

2024-06-01 15:59 UTC, maleyvich commented on code/modules/mob/dead/new_player/new_player.dm
> +			"Синтеты" = list(jobs = list(), titles = nonhuman_positions, color = "#ccffcc"),
о синтетическом разуме успели посмеяться еще в пр-е лехарка. но твое дело!

2024-06-01 16:00 UTC, maleyvich commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(usr, "<span class='notice'>Администрация отключила вступление в раунд!</span>")
войти как призрак не равно вступлению в раунд.

2024-06-21 10:41 UTC, AmnyamNyam requested changes

2024-06-21 10:41 UTC, AmnyamNyam commented on code/modules/mob/dead/new_player/new_player.dm
> +			to_chat(usr, "<span class='notice'>Администрация отключила вступление в раунд!</span>")
```suggestion
			to_chat(usr, "<span class='notice'>Администрация отключила возможность присоединиться в раунд!</span>")
```

2026-06-05 13:40 UTC, closed without merging