Fix ammo box
TauCetiStation-TranslationDepartment/TauCetiClassic pull request #35
Opened 2024-06-27 17:51 UTC by AzzyDreemurr13

## Описание изменений
fix https://github.com/TauCetiStation/TauCetiClassic/issues/13086
## Почему и что этот ПР улучшит
Наконец-то минус 1 проблема перевода
## Авторство
Я

## Чеинжлог

2024-06-27 18:05 UTC, Pivo24 requested changes
тут

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/boxes.dm
> +	cases = list("коробки патронов (Травматический)", "коробки патронов (Травматический)", "коробке патронов (Травматический)", "коробке патронов (Травматический)", "коробкой патронов (Травматический)",
падежи не те, тут травматы

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин СМГ (9мм)", "магазина СМГ (9мм)", "магазину СМГ (9мм)", "магазин СМГ (9мм)", "магазином СМГ (9мм)", "магазине СМГ (9мм)")
ПП, может?

СМГ как аббревиатура во что расшифруется? сабмашинган?

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +
тут ентер нажали уберите некрасиво!!!

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин дробовика (12г Картечь)", "магазина дробовика (12г Картечь)", "магазину дробовика (12г Картечь)", "магазин дробовика (12г Картечь)", "магазином дробовика (12г Картечь)", "магаз
может там барабан написать? типо это же ну натурально барабан в бульдоге

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин Дрозд (12.7мм)", "магазина Дрозда (12.7мм)", "магазину Дрозда (12.7мм)", "магазин Дрозд (12.7мм)", "магазином Дрозда(12.7мм)", "магазине Дрозда(12.7мм)")
во-первых магазин Дрозда

во-вторых что-то не так кажется с тем что это магазин Дрозда. Винтовочный/автоматный магазин какой-нибудь наверное..?

2024-06-27 18:05 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин М41А (10x24 Безкассетный)", "магазина М41А (10x24 Безкассетный)", "магазину М41А (10x24 Безкассетный)", "магазин М41А (10x24 Безкассетный)", "магазином М41А (10x24 Безкассетный
тут я немножко не знаю что такое Безкассетный ;-;

помогите пожалусто скиньте вики-ссылку как такие пули называются что гильз не оставляют

2024-06-27 18:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/boxes.dm
> +	cases = list("коробки патронов (Картечь)", "коробки патронов (Картечь)", "коробке патронов (Картечь)", "коробку патронов (Картечь)", "коробкой патронов (Картечь)", "коробке патронов (Картечь)")
Разве не должно все начинаться с именительного падежа?

2024-06-27 18:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +
Что-то потерялось!

2024-06-27 18:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин дробовика (12г Картечь)", "магазина дробовика (12г Картечь)", "магазину дробовика (12г Картечь)", "магазин дробовика (12г Картечь)", "магазином дробовика (12г Картечь)", "магаз
можно для брутальности обозвать его барабаном, ибо там как раз барабан

2024-06-27 18:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("маленький магазин А74 (7.74мм)", "маленького магазина А74 (7.74мм)", "маленькому магазину А74 (7.74мм)", "маленький магазин А74 (7.74мм)", "маленьким магазином А74 (7.74мм)", "маленько
Просто заметка: так не называют магазины. Обычно говорят что-то в стиле "Магазин на X патронов"

Не знаю как такое смотреться будет в реалиях сосаки именно твой вариант

2024-06-27 18:09 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин СМГ (9мм)", "магазина СМГ (9мм)", "магазину СМГ (9мм)", "магазин СМГ (9мм)", "магазином СМГ (9мм)", "магазине СМГ (9мм)")
ПП

2024-06-27 18:10 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин М41А (10x24 Безкассетный)", "магазина М41А (10x24 Безкассетный)", "магазину М41А (10x24 Безкассетный)", "магазин М41А (10x24 Безкассетный)", "магазином М41А (10x24 Безкассетный
Это безгильзовые патроны, которые, соответственно, не оставляют гильз.

2024-06-27 18:12 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин дробовика (12г Картечь)", "магазина дробовика (12г Картечь)", "магазину дробовика (12г Картечь)", "магазин дробовика (12г Картечь)", "магазином дробовика (12г Картечь)", "магаз
гении думоют одинаково

2024-07-04 16:28 UTC, Pivo24 requested changes

2024-07-04 16:28 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("магазин А28 (5.56мм Зажигателый)", "магазина А28 (5.56мм Зажигателый)", "магазину А28 (5.56мм Зажигателый)", "магазин А28 (5.56мм Зажигателый)", "магазином А28 (5.56мм Зажигателый)", "
Зажигательный*

2024-07-04 16:28 UTC, Pivo24 commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("барабан дробовика (12г Зажигателый)", "барабана дробовика (12г Зажигателый)", "барабану дробовика (12г Зажигателый)", "барабан дробовика (12г Зажигателый)", "барабаном дробовика (12г З
Зажигательный*

2024-07-04 16:28 UTC, Pivo24 commented on code/modules/projectiles/ammunition/boxes.dm
> +	desc = "коробки для патронов (Картечь) 12 калибра."
я правильно понял что Examine прокнет это?

> This is коробка патронов (Картечь)!
коробки для патронов (Картечь) 12 калибра.

desc смущает

2024-07-04 16:36 UTC, Pivo24 submitted a review, later dismissed

2024-07-08 09:17 UTC, AmnyamNyam requested changes

2024-07-14 20:09 UTC, Pivo24 approved these changes
Ружейные смутили немножко, но в целом всё годицца

2024-07-14 20:27 UTC, AmnyamNyam requested changes

2024-07-14 20:27 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	name = "small A74 magazine (7.74mm)"
```suggestion
	name = "small A74 magazine (7.74мм)"
```

2024-07-14 20:27 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("барабан дробовика (12г Картечь)", "барабана дробовика (12г Картечь)", "барабану дробовика (12г Картечь)", "барабан дробовика (12г Картечь)", "барабаном дробовика (12г Картечь)", "бараб
барабан дробовика?

Может от дробовика? И от какого? Надо корректировать. Ты же не можешь просто поместить в помповый дробовик барабан.

2024-07-14 20:27 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/magazines.dm
> +	cases = list("обойма патронов 7.74", "обоймы патронов 7.74", "обойме патронов 7.74", "обойму патронов 7.74", "обоймой патронов 7.74", "обойме патронов 7.74")
Скобки куда пропали?

2024-07-14 20:45 UTC, closed without merging